spring.application.name=Inventory

spring.datasource.url=jdbc:mysql://localhost:3306/inventario_udemy_db?createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=jeronimo12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
spring.jpa.show-sql=true

# Configurar el patrón de log
logging.pattern.console=[%thread] %-5level: %logger - %msg%n

# Configurar nivel del log
logging.level.root=INFO

# Opcional
# logging.level.gm.inventario=DEBUG
# logging.level.org.springframework=WARN

# Puerto del servidor
server.port=8080

# Desactivar banner de Spring
spring.main.banner-mode=off